inputs:
  bitbake_prefix:
    default: ''
  bitbake_target:
    default: 'cog'
  # SOURCE: raspberrypi3-mesa-wpe-2.38 raspberrypi3-mesa poky layers.python2.raspberrypi.qt5.webkit conf_v3.wpe-2_38
  bitbake_source:
    default: 'source'
  repo_release:
    default: 'kirkstone'
runs:
  using: 'composite'
  steps:
    - name: Print environment
      shell: bash
      run:  |
        echo "Environment:"
        echo "======================================================================"
        echo "BITBAKE_PREFIX=${{ inputs.bitbake_prefix }}"
        echo "BITBAKE_SOURCE=${{ inputs.bitbake_source }}"
        echo "BITBAKE_TARGET=${{ inputs.bitbake_target }}"
        echo "RELEASE=${{ inputs.repo_release }}"
        echo "======================================================================"
    - name: Build
      shell: bash
      run:  |
        cd ~/yocto-webkit-${{ inputs.repo_release }}
        ulimit -n 4096
        source sources/meta-webkit/.github/scripts/setup-environment ${{ inputs.bitbake_source }}
        rm -rf tmp
        ${{ inputs.bitbake_prefix }} bitbake ${{ inputs.bitbake_target }}
    - name: Clean the tmp dir
      if: always()
      shell: bash
      run:  |
        rm -rf ~/yocto-webkit-${{ inputs.repo_release }}/builds/*/tmp

