inputs:
  repo_url:
    default: https://github.com/${{ github.repository }}.git
  repo_ref:
    default: ${{ github.ref }}
  repo_release:
    default: 'kirkstone'
runs:
  using: 'composite'
  steps:
    - name: Print environment
      shell: bash
      run:  |
        echo "Environment:"
        echo "======================================================================"
        echo "CI_REPOSITORY_URL=${{ inputs.repo_url }}"
        echo "CI_COMMIT_SHA=${{ inputs.repo_ref }}"
        echo "CI_RELEASE=${{ inputs.repo_release }}"
        echo "======================================================================"
    - name: Set bitbake environment
      shell: bash
      run:  |
        sudo apt-get install -y git git-lfs repo
        mkdir -p ~/yocto-webkit-${{ inputs.repo_release }}
        cd ~/yocto-webkit-${{ inputs.repo_release }}
        repo init -u ${{ inputs.repo_url }} -m .github/manifest/manifest-${{ inputs.repo_release }}.xml -b ${{ inputs.repo_ref }}
        repo sync --force-sync
        pushd sources/meta-webkit
        git config --global user.email "meta-webkit-bot@igalia.com"
        git config --global user.name "meta-webkit CI Bot"
        git remote add tmp ${{ inputs.repo_url }}
        git fetch tmp ${{ github.base_ref }}
        git fetch tmp ${{ inputs.repo_ref }}:${{ inputs.repo_ref }}
        git checkout ${{ inputs.repo_ref }}
        git rebase tmp/${{ github.base_ref }}
        popd
    - name: Tar Work Dir
      shell: bash
      run:  |
        cd ~
        tar -cf yocto-webkit-${{ inputs.repo_release }}.tar yocto-webkit-${{ inputs.repo_release }}
    - name: Upload Tar Work Dir Artifact
      uses: actions/upload-artifact@v4
      with:
        name: yocto-webkit-${{ inputs.repo_release }}
        path:  ~/yocto-webkit-${{ inputs.repo_release }}.tar

