name: 'Close stale issues and PR'
on:
  schedule:
    - cron: '30 3 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open 90 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
          stale-pr-message: 'This PR is stale because it has been open 90 days with no activity.'
          close-issue-message: 'This issue was closed because it has been stale for 7 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stale for 7 days with no activity.'
          stale-issue-label: 'no-issue-activity'
          stale-pr-label: 'no-pr-activity'
          exempt-issue-labels: 'awaiting-approval,work-in-progress'
          exempt-pr-labels: 'awaiting-approval,work-in-progress'
          days-before-issue-stale: 90
          days-before-pr-stale: 90
          days-before-issue-close: 7
          days-before-pr-close: -1
