name: Build tests
on: [pull_request]
jobs:
  repo:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        yocto_release: ['wrynose']
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-repo
        with:
          repo_release: ${{ matrix.yocto_release }}

  build-wpe:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        yocto_release: ['wrynose']
        machine: ['qemuarm64', 'qemuarm', 'qemux86-64']
        yocto_prefix: ['TCLIBC=glibc']
        wpe_vers: ['2_54']
        include:
          - yocto_release: wrynose
            machine: qemuarm64
            yocto_prefix: TCLIBC=musl
            wpe_vers: 2_54
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_source: '${{ matrix.machine }}-wpe-${{ matrix.wpe_vers }} ${{ matrix.machine }} poky layers.webkit conf_v4.wpe-${{ matrix.wpe_vers }}'
          bitbake_prefix: ${{ matrix.yocto_prefix }}
          repo_release: ${{ matrix.yocto_release }}
    needs: repo

  build-gtk:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        yocto_release: ['wrynose']
        machine: ['qemuarm64', 'qemuarm', 'qemux86-64']
        yocto_prefix: ['TCLIBC=glibc']
        wpe_vers: ['2_54']
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_source: '${{ matrix.machine }}-wpe-${{ matrix.wpe_vers }} ${{ matrix.machine }} poky layers.webkit conf_v4.wpe-${{ matrix.wpe_vers }}'
          bitbake_target: webkitgtk
          bitbake_prefix: ${{ matrix.yocto_prefix }}
          repo_release: ${{ matrix.yocto_release }}
    needs: repo
