name: Build tests
on: [pull_request]
jobs:

  dunfell-repo:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-repo
        with:
          repo_release: 'dunfell'

  dunfell-raspberrypi3-mesa-weston-wpe-2-42:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_source: 'raspberrypi3-mesa-wpe-2-42 raspberrypi3-mesa poky layers.raspberrypi.clang.gstreamer.webkit conf_v1.wpe-2_42'
          repo_release: 'dunfell'
    needs: dunfell-repo

  kirkstone-repo:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-repo
        with:
          repo_release: 'kirkstone'

  kirkstone-raspberrypi3-mesa-weston-wpe-2-42:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_source: 'raspberrypi3-mesa-wpe-2-40 raspberrypi3-mesa poky layers.raspberrypi.webkit conf_v3.wpe-2_42'
          repo_release: 'kirkstone'
    needs: kirkstone-repo

  nanbield-repo:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-repo
        with:
          repo_release: 'nanbield'

  nanbield-raspberrypi3-mesa-weston-wpe-2-42:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_source: 'raspberrypi3-mesa-wpe-2-42 raspberrypi3-mesa poky layers.raspberrypi.webkit conf_v4.wpe-2_42'
          repo_release: 'nanbield'
    needs: nanbield-repo

  nanbield-raspberrypi3-mesa-weston-wpe-qt:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_source: 'raspberrypi3-mesa-wpe-qt raspberrypi3-mesa poky layers.raspberrypi.qt5.webkit conf_v4.wpe-2_42.qt'
          repo_release: 'nanbield'
    needs: nanbield-repo

  nanbield-raspberrypi3-mesa-weston-wpe-musl:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_source: 'raspberrypi3-mesa-wpe-musl raspberrypi3-mesa poky layers.raspberrypi.webkit conf_v4.wpe-2_42'
          bitbake_prefix: 'TCLIBC=musl'
          repo_release: 'nanbield'
    needs: nanbield-repo

  nanbield-raspberrypi3-mesa-weston-wpe-2-40:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_source: 'raspberrypi3-mesa-wpe-2-40 raspberrypi3-mesa poky layers.raspberrypi.webkit conf_v4.wpe-2_40'
          repo_release: 'nanbield'
    needs: nanbield-repo

  nanbield-raspberrypi3-mesa-weston-gtk:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_source: 'raspberrypi3-mesa-webkitgtk raspberrypi3-mesa poky layers.raspberrypi.webkit conf_v4'
          bitbake_target: 'webkitgtk'
          repo_release: 'nanbield'
    needs: nanbield-repo

  nanbield-raspberrypi4-64-weston-wpe-2-42:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_source: 'raspberrypi4-64-wpe-2-42 raspberrypi4-64 poky layers.raspberrypi.webkit conf_v4.wpe-2_42'
          repo_release: 'nanbield'
    needs: nanbield-repo
