name: Build tests
on: [pull_request]
jobs:
  kirkstone-repo:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-repo
        with:
          repo_release: 'kirkstone'

  kirkstone-raspberrypi3-mesa-weston-wpe-2-38:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_source: 'raspberrypi3-mesa-wpe-2-38 raspberrypi3-mesa poky layers.raspberrypi.webkit conf_v3.wpe-2_38'
          repo_release: 'kirkstone'
    needs: kirkstone-repo

  kirkstone-raspberrypi3-mesa-weston-wpe-qt:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_source: 'raspberrypi3-mesa-wpe-qt raspberrypi3-mesa poky layers.raspberrypi.qt5.webkit conf_v3.wpe-2_38.qt'
          repo_release: 'kirkstone'
    needs: kirkstone-repo

  kirkstone-raspberrypi3-mesa-weston-wpe-musl:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_source: 'raspberrypi3-mesa-wpe-musl raspberrypi3-mesa poky layers.raspberrypi.webkit conf_v3.wpe-2_38'
          bitbake_prefix: 'TCLIBC=musl'
          repo_release: 'kirkstone'
    needs: kirkstone-repo

  kirkstone-raspberrypi3-mesa-weston-wpe-2-36:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_source: 'raspberrypi3-mesa-wpe-2-36 raspberrypi3-mesa poky layers.raspberrypi.webkit conf_v3.wpe-2_36'
          repo_release: 'kirkstone'
    needs: kirkstone-repo

  kirkstone-raspberrypi4-64-weston-wpe-2-38:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_source: 'raspberrypi4-64-wpe-2-38 raspberrypi4-64 poky layers.raspberrypi.webkit conf_v3.wpe-2_38'
          repo_release: 'kirkstone'
    needs: kirkstone-repo

  kirkstone-raspberrypi3-mesa-weston-gtk:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_source: 'raspberrypi3-mesa-webkitgtk raspberrypi3-mesa poky layers.raspberrypi.webkit conf_v3'
          bitbake_target: 'webkitgtk'
          repo_release: 'kirkstone'
    needs: kirkstone-repo

  dunfell-repo:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-repo
        with:
          repo_release: 'dunfell'

  dunfell-raspberrypi3-mesa-weston-wpe-2-38:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_source: 'raspberrypi3-mesa-wpe-2-38 raspberrypi3-mesa poky layers.raspberrypi.gstreamer.webkit conf_v1.wpe-2_38'
          repo_release: 'dunfell'
    needs: dunfell-repo

  langdale-repo:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-repo
        with:
          repo_release: 'langdale'

  langdale-raspberrypi3-mesa-weston-wpe-2-38:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_source: 'raspberrypi3-mesa-wpe-2-38 raspberrypi3-mesa poky layers.raspberrypi.webkit conf_v3.wpe-2_38'
          repo_release: 'langdale'
    needs: langdale-repo

