name: Build tests
on: [pull_request]
jobs:

  kirkstone-repo:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-repo
        with:
          repo_release: 'kirkstone'

  kirkstone-raspberrypi3-mesa-weston-wpe-2-46:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_source: 'raspberrypi3-mesa-wpe-2-46 raspberrypi3-mesa poky layers.raspberrypi.webkit conf_v3.wpe-2_46'
          repo_release: 'kirkstone'
    needs: kirkstone-repo

  scarthgap-repo:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-repo
        with:
          repo_release: 'scarthgap'

  scarthgap-matrix-wpe-2-46:
    strategy:
      fail-fast: false
      matrix:
        machine: ['raspberrypi3-mesa', 'raspberrypi4-64']
        wpe_vers: ['2_46']
        yocto_rel: ['scarthgap']
    continue-on-error: true
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    needs: scarthgap-repo
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_source: '${{ matrix.machine }}-wpe-${{ matrix.wpe_vers }} ${{ matrix.machine }} poky layers.raspberrypi.webkit conf_v3.wpe-${{ matrix.wpe_vers }}'
          repo_release: ${{ matrix.yocto_rel }}

  scarthgap-raspberrypi3-mesa-weston-wpe-musl:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_source: 'raspberrypi3-mesa-wpe-musl raspberrypi3-mesa poky layers.raspberrypi.webkit conf_v4.wpe-2_46'
          bitbake_prefix: 'TCLIBC=musl'
          repo_release: 'scarthgap'
    needs: scarthgap-repo

  scarthgap-raspberrypi3-mesa-weston-wpe-2-44:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_source: 'raspberrypi3-mesa-wpe-2-44 raspberrypi3-mesa poky layers.raspberrypi.webkit conf_v4.wpe-2_44'
          repo_release: 'scarthgap'
    needs: scarthgap-repo

  scarthgap-raspberrypi3-mesa-weston-gtk:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_source: 'raspberrypi4-64-webkitgtk raspberrypi4-64 poky layers.raspberrypi.webkit conf_v4'
          bitbake_target: 'webkitgtk'
          repo_release: 'scarthgap'
    needs: scarthgap-repo

