name: Build tests
on: [pull_request]
jobs:
  repo:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        yocto_release: ['scarthgap', 'whinlatter']
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-repo
        with:
          repo_release: ${{ matrix.yocto_release }}

  build-wpe:
    runs-on: self-hosted
    continue-on-error: ${{ matrix.yocto_release == 'whinlatter' }}
    strategy:
      fail-fast: false
      matrix:
        yocto_release: ['scarthgap', 'whinlatter']
        machine: ['raspberrypi3-mesa', 'raspberrypi4-64']
        yocto_prefix: ['TCLIBC=glibc']
        wpe_vers: ['2_50']
        include:
          - yocto_release: scarthgap
            machine: raspberrypi4-64
            yocto_prefix: TCLIBC=musl
            wpe_vers: 2_50
          - yocto_release: whinlatter
            machine: raspberrypi4-64
            yocto_prefix: TCLIBC=musl
            wpe_vers: 2_50
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_source: '${{ matrix.machine }}-wpe-${{ matrix.wpe_vers }} ${{ matrix.machine }} poky layers.raspberrypi.webkit conf_v4.wpe-${{ matrix.wpe_vers }}'
          repo_release: ${{ matrix.yocto_release }}
    needs: repo

  build-gtk:
    runs-on: self-hosted
    continue-on-error: ${{ matrix.yocto_release == 'whinlatter' }}
    strategy:
      fail-fast: false
      matrix:
        yocto_release: ['scarthgap', 'whinlatter']
        machine: ['raspberrypi3-mesa', 'raspberrypi4-64']
        yocto_prefix: ['TCLIBC=glibc']
        wpe_vers: ['2_50']
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_source: '${{ matrix.machine }}-wpe-${{ matrix.wpe_vers }} ${{ matrix.machine }} poky layers.raspberrypi.webkit conf_v4.wpe-${{ matrix.wpe_vers }}'
          bitbake_target: webkitgtk
          repo_release: ${{ matrix.yocto_release }}
    needs: repo
